// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSizeRatio():Promise<number>;

export function IsLoaded():Promise<boolean>;

export function SetSizeRatio(arg1:number):Promise<void>;
