// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendMessage(arg1:string):Promise<void>;

export function SetFullInputMode(arg1:boolean):Promise<void>;

export function SetTyping(arg1:boolean):Promise<void>;
