// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {options} from '../models';

export function Load():Promise<options.Config>;

export function Save(arg1:options.Config):Promise<void>;
