// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tts} from '../models';
import {aivis} from '../models';
import {pages} from '../models';

export function GetAudioDevice():Promise<Array<tts.Device>>;

export function GetSpackers():Promise<Array<aivis.Speaker>>;

export function IsRunning():Promise<boolean>;

export function ReadLog():Promise<string>;

export function SaveAudioDevice(arg1:string):Promise<void>;

export function SaveSpacker(arg1:number):Promise<void>;

export function SelectedSpacker():Promise<pages.SelectedSpackerRsp>;
