// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAudioDevice() {
  return window['go']['pages']['TTS']['GetAudioDevice']();
}

export function GetSpackers() {
  return window['go']['pages']['TTS']['GetSpackers']();
}

export function IsRunning() {
  return window['go']['pages']['TTS']['IsRunning']();
}

export function ReadLog() {
  return window['go']['pages']['TTS']['ReadLog']();
}

export function SaveAudioDevice(arg1) {
  return window['go']['pages']['TTS']['SaveAudioDevice'](arg1);
}

export function SaveSpacker(arg1) {
  return window['go']['pages']['TTS']['SaveSpacker'](arg1);
}

export function SelectedSpacker() {
  return window['go']['pages']['TTS']['SelectedSpacker']();
}
