name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: wailsBuild, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
          go-version: 1.24.4
